//Two part query playbook for scoping relevant logs at a wide range and then narrowing.  Always consider your time frame when scoping.
//Consider start time to be a few hours before and the end time a few hours after the expected time of an incident or investigation.
//Run the top query first.  Using the most relevant tables from the first query, input into the second query.
//Input values you want to search including IOCs, IP addresses, hashes, applications and urls related to the incident or threat you are investigating.
search in ("<value>", "<value>", "<value>")
//Show all tables that appear from the values you input along with the number of times they appear.
| summarize count() by $table

//Use the union operator and enter the most relevant table names that appeared in the first query's results for the investigation.
union table, table, table
//Input the same values from the first query.  
| search in ("<value>", "<value>", "<value>")
| project table, table, table
